// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZl1CioTBl1p0YfIRghtGg0iihin0jkzc',
    appId: '1:997969979034:web:1c79ec89383fd807dba123',
    messagingSenderId: '997969979034',
    projectId: 'ig-project-df55f',
    authDomain: 'ig-project-df55f.firebaseapp.com',
    storageBucket: 'ig-project-df55f.appspot.com',
    measurementId: 'G-S02F7JBWX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Adm42mRFHAADYj5Og5GM7F50Nbsaq5Y',
    appId: '1:997969979034:android:592bf19dbe7035d7dba123',
    messagingSenderId: '997969979034',
    projectId: 'ig-project-df55f',
    storageBucket: 'ig-project-df55f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsBgDmhC9mwTHQwa13HAejMReKPN473Fg',
    appId: '1:997969979034:ios:d2ecef0a0702be8cdba123',
    messagingSenderId: '997969979034',
    projectId: 'ig-project-df55f',
    storageBucket: 'ig-project-df55f.appspot.com',
    iosClientId: '997969979034-9dfc982irafhhb1v15tr2qfqhggeb72t.apps.googleusercontent.com',
    iosBundleId: 'com.example.igProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsBgDmhC9mwTHQwa13HAejMReKPN473Fg',
    appId: '1:997969979034:ios:d2ecef0a0702be8cdba123',
    messagingSenderId: '997969979034',
    projectId: 'ig-project-df55f',
    storageBucket: 'ig-project-df55f.appspot.com',
    iosClientId: '997969979034-9dfc982irafhhb1v15tr2qfqhggeb72t.apps.googleusercontent.com',
    iosBundleId: 'com.example.igProject',
  );
}
